os: linux
dist: bionic

#install google chrome, using addons
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

language: node_js
node_js:
- "8"

services:
- xvfb

before_script:
- npm install --quiet -g gulp-cli
- npm install codecov -g

script: gulp test:ci

after_success:
- gulp coveralls
- codecov

cache:
  yarn: true
